//plain=TYPES.PLAIN, ribbon=TYPES.RIBBON, animal=TYPES.ANIMAL, bright=TYPES.BRIGHT
const TYPES = {
    'PLAIN': 0,
    'RIBBON': 1,
    'ANIMAL': 2,
    'BRIGHT': 3
}

const EACH_TYPE = [
    [], //just so that index matches w/ month
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.RIBBON, TYPES.BRIGHT], //jan
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.RIBBON, TYPES.ANIMAL], //feb
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.RIBBON, TYPES.BRIGHT], //mar
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.RIBBON, TYPES.ANIMAL], //apr
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.RIBBON, TYPES.ANIMAL], //may
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.RIBBON, TYPES.ANIMAL], //jun
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.RIBBON, TYPES.ANIMAL], //jul
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.ANIMAL, TYPES.BRIGHT], //aug
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.RIBBON, TYPES.ANIMAL], //sep
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.RIBBON, TYPES.ANIMAL], //oct
    [TYPES.PLAIN, TYPES.RIBBON, TYPES.RIBBON, TYPES.BRIGHT], //nov
    [TYPES.PLAIN, TYPES.PLAIN, TYPES.PLAIN, TYPES.BRIGHT]  //dec
];

export function getCardType(month, index) {
    return EACH_TYPE[month][index];
}