const TYPES = {
    'KASU': 0,
    'TANZAKU': 1,
    'TANE': 2,
    'GOKO': 3
}

const EACH_TYPE = [
    [], //just so that index matches w/ month
    [TYPES.KASU, TYPES.KASU, TYPES.TANZAKU, TYPES.GOKO],    //jan
    [TYPES.KASU, TYPES.KASU, TYPES.TANZAKU, TYPES.ANIMAL],  //feb
    [TYPES.KASU, TYPES.KASU, TYPES.TANZAKU, TYPES.GOKO],    //mar
    [TYPES.KASU, TYPES.KASU, TYPES.TANZAKU, TYPES.ANIMAL],  //apr
    [TYPES.KASU, TYPES.KASU, TYPES.TANZAKU, TYPES.ANIMAL],  //may
    [TYPES.KASU, TYPES.KASU, TYPES.TANZAKU, TYPES.ANIMAL],  //jun
    [TYPES.KASU, TYPES.KASU, TYPES.TANZAKU, TYPES.ANIMAL],  //jul
    [TYPES.KASU, TYPES.KASU, TYPES.ANIMAL, TYPES.GOKO],     //aug
    [TYPES.KASU, TYPES.KASU, TYPES.TANZAKU, TYPES.ANIMAL],  //sep
    [TYPES.KASU, TYPES.KASU, TYPES.TANZAKU, TYPES.ANIMAL],  //oct
    [TYPES.KASU, TYPES.TANZAKU, TYPES.TANZAKU, TYPES.GOKO], //nov
    [TYPES.KASU, TYPES.KASU, TYPES.KASU, TYPES.GOKO]        //dec
];

export function getCardType(month, index) {
    return EACH_TYPE[month][index];
}